# Cloud Build configuration for Kairos Control Plane
# Builds and deploys to Cloud Run

substitutions:
  _SERVICE_NAME: kairos-control-plane
  _REGION: us-central1
  _GKE_NAMESPACE: frappe
  _BASE_DOMAIN: kairos.app
  _GKE_CLUSTER: kairos-cluster-dev
  _GKE_LOCATION: us-central1

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'BASE_DOMAIN=${_BASE_DOMAIN},GKE_NAMESPACE=${_GKE_NAMESPACE},USE_IN_CLUSTER=false,GKE_PROJECT=$PROJECT_ID,GKE_CLUSTER=${_GKE_CLUSTER},GKE_LOCATION=${_GKE_LOCATION}'
      - '--set-secrets'
      - 'API_KEY=kairos-api-key:latest,WEBHOOK_SECRET=kairos-webhook-secret:latest'
      - '--service-account'
      - 'kairos-control-plane@$PROJECT_ID.iam.gserviceaccount.com'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
